name: ci

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am
  push:
    branches:
      - master

jobs:
 ecr:
   runs-on: ${{ matrix.os }}
   strategy:
     fail-fast: false
     matrix:
       os:
         - ubuntu-20.04
         - ubuntu-18.04
         - ubuntu-16.04
   steps:
     -
       name: Checkout
       uses: actions/checkout@v2
     -
       name: Login to ECR
       uses: ./
       with:
         registry: ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
         username: ${{ secrets.AWS_ACCESS_KEY_ID }}
         password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         arn: ${{ secrets.AWS_ARN }}

